### ISSUE TITLE
Add LeetCode - 142. Linked List Cycle II in C++

### ISSUE THREAD

**Issue by NafiAsib** [Tahanima/leetcode-solution-curation#47]
I want to provide solution to the problem [Linked List Cycle II](https://leetcode.com/problems/linked-list-cycle-ii/) in C++.

**Comment by NafiAsib** [comment]
@Tahanima will you assign the issue or should I just create a PR?

**Comment by Tahanima** [comment]
@NafiAsib, go ahead with your PR. Also, I've assigned you to this issue!
